kind: Service
apiVersion: v1
metadata:
  name: basic-auth
spec:
  selector:
    app:  basic-auth
  type:  NodePort
  ports:
  - protocol: TCP
    port:  80
    targetPort:  http
    nodePort: 30060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-auth
spec:
  selector:
    matchLabels:
      app: basic-auth
  template:
    metadata:
      labels:
        app: basic-auth
    spec:
      containers:
      - name: nginx
        image: "gihyodocker/nginx:latest"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        env:
          - name: BACKEND_HOST
            value: "localhost:8080"
          - name: BASIC_AUTH_FILE
            value: "/etc/nginx/secret/secretKey"
        volumeMounts:
          - mountPath: /etc/nginx/secret
            name: nginx-secret
            readOnly: true
      - name: echo
        image: "gihyodocker/echo:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
         - name: HTTP_PORT
           value: "8080"
      volumes:
        - name: nginx-secret
          secret:
              secretName: nginx-secret

